### ISSUE TITLE
旗帜图案部分汉化有误

### ISSUE THREAD

**Issue by Steve41149** [vlssu/Mine-imator-Chinese#2]
### Mine-imator 版本

2.0.1

### 汉化错误文本

```text
“half_vertical”: "右半方形"
“half_vertical_right”: "左半方形"
```

### 纠正后文本

```text
“half_vertical”: "左半方形"
“half_vertical_right”: "右半方形"
```

**Comment by vlssu** [comment]
谢谢你的反馈，已进行修正（minecraftwiki那边多半也是左右写错了）

**Comment by Steve41149** [comment]
我在做另一版汉化的时候我突然发现旗帜部分下方所有显示出来的名字和前面的变量名左右都写反了，感觉有可能是wiki写反了也有可能是mi那边的开发人员写语言文件的时候写反了

从 Windows 版邮件发送

发件人: 飒爽师叔
发送时间: 2023年11月12日 5:50
收件人: vlssu/Mine-imator-Chinese
抄送: Steve41149; Author
主题: Re: [vlssu/Mine-imator-Chinese] 旗帜图案部分汉化有误 (Issue #2)

谢谢你的反馈，已进行修正（minecraftwiki那边多半也是左右写错了）

**Comment by vlssu** [comment]
应该是 wiki 那边写反了，releases 已重新上传

**Comment by Steve41149** [comment]
破案了，mojang的问题
游戏里面的盾牌和旗帜的样式是反过来的
mi里面是按照实际填写的
