### ISSUE TITLE
改进部分

### ISSUE THREAD

**Issue by Steve41149** [vlssu/Mine-imator-Chinese#3]
### Mine-imator 版本

2.0.1

### 汉化错误文本

```text
"escape": "esc",
"backspace": "删除键",
"delete": "delete",
"insert": "insert",
"pageup": "page up",
"pagedown": "page down",
"pause": "pasue",
"Printscreen": "Printscreen","
```

### 纠正后文本

```text
"escape": "退出键",
"backspace": "退格键",
"delete": "删除键",
"insert": "替换键",
"pageup": "上翻页键",
"pagedown": "下翻页键",
"pause": "暂停键",
"Printscreen": "截图键"

顺便一提，虽然影响不大，但是有一些文本出现了缩进问题（不知道是不是我vim的问题，我在vim上看出现了缩进不齐的问题）
在"tab"{和"key"{下所出现
```

**Comment by vlssu** [comment]
这里没有汉化是我觉得没有必要汉化？
因为不是所有人都知道esc之类的是退出键，他们还需要再去查网络是对应键盘的哪个键，我原设想的是修改成键盘对应的英文，这样用户也好找？
当然汉化了也无伤大雅😂

**Comment by vlssu** [comment]
vim显示不齐很正常，因为它不像其他的编辑器能将tab缩进之类的很好的对齐。
其实你应该用VS code的，使用vim编辑器你不觉得很累吗？😂

**Comment by Steve41149** [comment]
gvim可以用tab啊（
vim对我而言感觉用这挺爽的，vs倒是没用过
我之前用的是notepad next（
以及我往vim上丢了一点插件用起来体验还算不错，就是学习成本有点偏高，但是问题不大

------------------ 原始邮件 ------------------
From: 飒爽师叔 ***@***.***&gt;
发送时间: 11/12/2023, 18:45
To: vlssu/Mine-imator-Chinese ***@***.***&gt;
抄送: Steve41149 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [vlssu/Mine-imator-Chinese] 改进部分 (Issue #3)





 
vim显示不齐很正常，因为它不像其他的编辑器能将tab缩进之类的很好的对齐。
 其实你应该用VS code的，使用vim编辑器你不觉得很累吗？😂

**Comment by Steve41149** [comment]
是这样，可能我的脑回路比较新奇吧
毕竟我写的梗体中文（





------------------ 原始邮件 ------------------
From: 飒爽师叔 ***@***.***&gt;
发送时间: 11/12/2023, 16:57
To: vlssu/Mine-imator-Chinese ***@***.***&gt;
抄送: Steve41149 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [vlssu/Mine-imator-Chinese] 改进部分 (Issue #3)





 
这里没有汉化是我觉得没有必要汉化？
 因为不是所有人都知道esc之类的是退出键，他们还需要再去查网络是对应键盘的哪个键，我原设想的是修改成键盘对应的英文，这样用户也好找？
 当然汉化了也无伤大雅😂

**Comment by vlssu** [comment]
已根据你的建议修改部分译文 https://github.com/vlssu/Mine-imator-Chinese/commit/fd66b6de9a82284ced76e633407021052b8178d8

将大家都熟知的改为中文，但是因为使用习惯，我们不也不会将esc键说成退出键，毕竟控制页的设置，是给用户去找键盘的键而不是让他们一脸懵逼，所以我这里就改了部分并保留英文，这样两全其美？😁
