### ISSUE TITLE
没错还是我，您汉化不出意外的又双叒叕出意外了（

### ISSUE THREAD

**Issue by Steve41149** [vlssu/Mine-imator-Chinese#6]
### Mine-imator 版本

2.0.1

### 汉化错误文本

```text
1953行
"netherite_block": "下界合金锭"
```

### 纠正后文本

```text
"netherite_block": "下界合金块"
```

**Comment by vlssu** [comment]
哈哈哈，好家伙发自我的手机-------- 原始邮件 --------发件人： Steve41149 ***@***.***>日期： 2024年1月13日周六 18:51收件人： vlssu/Mine-imator-Chinese ***@***.***>抄送： Subscribed ***@***.***>主    题： [vlssu/Mine-imator-Chinese] 没错还是我，您汉化不出意外的又双叒叕出意外了（ (Issue #6)
Mine-imator 版本
2.0.1
汉化错误文本
1953行
"netherite_block": "下界合金锭"

纠正后文本
"netherite_block": "下界合金块"
